name: AEM Code Sync

on: 
 workflow_dispatch:
    
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
          
      - name: Code Sync
        run: |
           sudo apt-get install -y unzip git
           sudo git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           sudo git config credential.username ${{ secrets.GIT_USER }}
           sudo git config credential.helper ${{ secrets.GIT_PAT }}
           sudo git remote -v
           sudo git fetch --unshallow
           sudo git checkout main
           sudo git pull 
           sudo git filter-branch -- --all
           sudo git push poc main
           echo This is new change
        shell: bash
        

           
        
