name: TestSync

on: workflow_dispatch

jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_PAT }}
                
      - name: Code Sync to develop branch
        if: github.ref == 'refs/heads/develop'
        run: |
           sudo apt-get install -y unzip git
           sudo git remote add poc https://github.com/Vranda1188/AEM-Remote.git
           sudo git config credential.username ${{ secrets.GIT_USER }}
           sudo git config credential.helper ${{ secrets.GIT_PAT }}
           sudo git remote -v
           sudo git checkout develop
           sudo git branch -r | grep -v '\->' | while read remote; do sudo git branch --track "#{remote#origin/}" "$remote"; done
           sudo git fetch --all
           sudo git pull --all
           sudo git push -f -u poc develop
        shell: bash
